version: '3'

name: ed-45-adminer

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pruebas
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - mysql80_data:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql

volumes:
  mysql80_data: