version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pruebas
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - mysql80_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql

volumes:
  mysql80_data: